CREATE DATABASE IF NOT EXISTS asset;
USE asset;
CREATE TABLE IF NOT EXISTS user_asset (
  id BIGINT AUTO_INCREMENT NOT NULL,
  user_id BIGINT NOT NULL COMMENT 'User ID',
  token VARCHAR(20) NOT NULL COMMENT 'Token',
  balance DECIMAL(26,8) DEFAULT 0.0 COMMENT 'Balance',
  locked DECIMAL(26,8) DEFAULT 0.0 COMMENT 'Locked',
  last_update_id BIGINT COMMENT 'Last update ID'
  created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  modified_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY user_token (user_id, token)
);

CREATE TABLE IF NOT EXISTS user_asset_log (
  id BIGINT AUTO_INCREMENT NOT NULL,
  user_id BIGINT NOT NULL COMMENT 'User ID',
  token VARCHAR(20) NOT NULL COMMENT 'Token',
  delta DECIMAL(26,8) DEFAULT 0.0 COMMENT 'Delta',
  tx_type VCHAR(20) COMMENT 'Transaction type: DEPOSIT, WITHDRAW, TRANSFER, LOCK, UNLOCK',
  created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  modified_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
);